### ISSUE TITLE
Crear Subasta - No existe una longitud máxima para ninguno de los campos

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#10]
Pasos para reproducir:
1. Iniciar sesión en el sistema.
2. Elegir crear una subasta.
3. Incluir más una cantidad de caracteres excesiva (100 o más) en cualquiera de los campos de texto.
4. Confirmar la creación.

Resultado: La subasta se crea con éxito, a pesar de la excesiva longitud de los datos ingresados.
Resultado Esperado: Una validación impide que se cree la subasta cuando cualquier dato suministrado es demasiado largo.

Nota: Las longitudes de campos no están especificadas en las historias de usuario y se deberá acordar una longitud máxima para cada campo.

**Comment by mgiagante** [comment]
Arreglado en commit 9779a39edc39decda54841c8af3fd54a5f47f600

**Comment by braiandickson** [comment]
Revisado.
