### ISSUE TITLE
Registro - Falta la traducción del mensaje de error de la validación de que el email sea único.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#11]
Pasos para reproducir:
1. Ir a Regístrate.
2. Ingresar un email ya ingresado durante la creación de otro usuario.
3. Confirmar el registro.

Resultado: Se muestra un mensaje diciendo que el mensaje de error correspondiente al campo email no está traducido. Se muestra "translation missing:  es.activerecord.errors.models.user.attributes.email.taken".
Resultado Esperado: El mensaje de error tiene una traducción correcta.

**Comment by mgiagante** [comment]
Arreglado en commit 9779a39edc39decda54841c8af3fd54a5f47f600

**Comment by braiandickson** [comment]
Revisado.
