### ISSUE TITLE
Low - Detalle de Subasta - Las descripciones largas se salen de la caja.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#12]
Pasos para reproducir:
1. Iniciar sesión en el sistema.
2. Crear una subasta con una descripción que incluya el máximo de caracteres permitido.
3. Ver el detalle de la subasta.

Resultado: El texto de la descripción se sale de la caja.
Resultado Esperado: El texto se muestra correctamente.

**Comment by mgiagante** [comment]
![bug](https://cloud.githubusercontent.com/assets/5287175/8265861/5df5e69e-16e3-11e5-94d1-dc837ca0874d.png)

**Comment by braiandickson** [comment]
Rompe el formato cuando la descripcion contiene una palabra larga larga sin espacios. Con espacios el texto se acomoda acorde al bloque.

**Comment by mgiagante** [comment]
Pasa solo con palabras muy largas. Pendiente de fix.

**Comment by mgiagante** [comment]
KS
