### ISSUE TITLE
Preguntas/Respuestas - Se puede guardar una respuesta vacía.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#15]
Pasos para reproducir:
1. Iniciar sesión en el sistema con el usuario A.
2. Crear una subasta.
3. Cerrar sesión.
4. Iniciar sesión con el usuario B.
5. Ver el detalle de la subasta del paso 2 y hacer una pregunta.
6. Cerrar sesión.
7. Iniciar sesión con el usuario A.
8. Contestar a la pregunta con una respuesta vacía.

Resultado: La respuesta es aceptada.
Esperado: El sistema valida que la respuesta no esté vacía.

**Comment by hugotonelli** [comment]
Corregido en [master c27c76f]. Por favor revisar que funcione como se espera.

**Comment by mgiagante** [comment]
Verificado. Cerrando.
