### ISSUE TITLE
Ofertar - El dueño de una subasta puede hacer ofertas en su propia publicación

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#19]
Pasos:
1. Iniciar sesión
2. Crear una nueva subasta
3. Entrar al detalle de la subasta creada en el paso 2
4. Ingresar una razón y un monto para ofertar
5. Hacer click en "ofertar"

Resultado:
El dueño de una subasta puede hacer ofertas en su propia publicación.
Esperado:
El formulario de ofertar no se muestra en los detalles de subastas pertenecientes al usuario actual.

**Comment by braiandickson** [comment]
Revisado.
