### ISSUE TITLE
Low - Algunos errores de validación en el registro de nuevo usuario no están traducidos.

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#2]
Pasos para reproducir:
1. Seleccionar la opción de registro de usuario en la pantalla principal como invitado.
2. Ingresar datos con formato inválido en los diferentes campos.
3. Hacer click en "Registrarse"

Resultado: Se muestran mensajes de falta de traducción de errores de Active Record.
Resultado esperado: Todos los mensajes de error de validación se muestran correctamente en el idioma del sitio.

Notas:
- E-mail inválido (por ej: "@dominio.com") se muestra como "translation missing: es.activerecord.errors.models.user.attributes.email.invalid"
- Contraseña demasiado corta (por ej: "hola") se muestra como "translation missing: es.activerecord.errors.models.user.attributes.password.too_short"
- Confirmar contraseña no coincide (por ej: "password"->"pass") se muestra como "translation missing: es.activerecord.errors.models.user.attributes.password_confirmation.confirmation"
- Se adjunta captura de pantalla mostrando dichos errores.

![screenshot from 2015-06-08 16 18 33](https://cloud.githubusercontent.com/assets/11665876/8043443/96704cfc-0dfc-11e5-87fd-d463af6a8984.png)

**Comment by mgiagante** [comment]
Arreglado en el commit [master e382f2b] para los errores mencionados en el bug. Por favor buscar otros posibles casos en el registro antes de cerrar.

**Comment by hugotonelli** [comment]
Confirmadas las correcciones mencionadas.
Se mantiene abierto hasta corregir el error de contraseña muy larga encontrado en regresión, detallado más abajo.

String de error:
- translation missing: es.activerecord.errors.models.user.attributes.password.too_long

**Comment by hugotonelli** [comment]
Arreglado en el commit [master c66c6fb] para contraseña demasiado larga.

**Comment by mgiagante** [comment]
Verificado.
