### ISSUE TITLE
Ganador - Un usuario que no es dueño de la subasta puede elegir el ganador

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#20]
Pasos:
1. Asegurarse que haya subastas creadas por otros usuarios que tengan ofertas
2. Iniciar sesión
3. Entrar al detalle de una subasta creada por otro usuario que tenga ofertas
4. Hacer click en "Ganador"
5. Hacer click en "Seleccionar ganador" en la ventana con la lista de ofertas del producto subastado

Resultado:
Un usuario puede elegir el ganador de subastas pertenecientes a otros usuarios
Esperado:
Sólo el usuario dueño de la subasta puede elegir un ganador

**Comment by braiandickson** [comment]
Revisado.
