### ISSUE TITLE
Medium - Global - Las URLs inválidas arrojan excepción y dump

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#23]
Pasos:
1. Ingresar una URL inválida dentro del dominio

Resultado:
Se levanta una excepción y se muestra un dump por la dirección inválida
Esperado:
Se muestra un mensaje de error entendible para el usuario y se provee una manera de salir del estado de error

Notas:
- Actualmente hay 2 variantes de URL inválidas: métodos no registrados en la tabla de ruteo (por ej.: escribir cualquier secuencia aleatoria de caracteres luego de la URL del dominio); y valores inválidos (por ej: modificar la ruta de detalle de un producto para intentar acceder al detalle de un producto inexistente)

**Comment by mgiagante** [comment]
Lamentablemente KS por falta de tiempo.
