### ISSUE TITLE
Medium - Eliminar usuario - No se deshabilita la eliminación de usuarios con subastas activas

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#24]
Pasos:
1. Iniciar sesión
2. Crear una subasta
3. Ir a "Mi cuenta"
4. Seleccionar la opción de eliminar usuario y aceptar la notificación.

Resultado:
Se permite la eliminación de usuarios con subastas activas, generando una excepción y dump al intentar mostrar las subastas activas.
Esperado:
Se notifica al usuario que no puede eliminar su cuenta mientras tenga subastas activas.

**Comment by mgiagante** [comment]
Arreglado. El link de la página de edición de cuenta ya no se habilita si el usuario tiene subastas activas que haya creado. Por favor verificar fix.

**Comment by hugotonelli** [comment]
Verificado. El link ya no es clickeable si hay subastas pendientes.
