### ISSUE TITLE
Medium - Ofertar - La oferta del usuario invitado no se genera al finalmente iniciar sesión

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#25]
Pasos:
1. Entrar como invitado a la página de detalle de una subasta activa
2. Ingresar una oferta en los campos de "Razón" y "Monto"
3. Hacer click en "Ofertar"
4. Ingresar los datos de inicio de sesión al momento de ser solicitados

Resultado:
La oferta del usuario invitado no se genera al finalmente iniciar sesión, perdiendo la información ingresada en el formulario y sin tener una notificación clara al respecto.
Esperado:
No se generan situaciones en las que datos válidos ingresados se pierdan sin notificaciones.

Notas:
- Puede resolverse extendiendo el mensaje de error que se muestra junto con la pantalla de inicio de sesión, avisándole al usuario que vuelva a intentar una vez iniciada su sesión
- Puede (preferiblemente) mostrársele al usuario un mensaje de que debe iniciar sesión para ofertar en lugar del formulario de oferta

**Comment by mgiagante** [comment]
Arreglado en commit [master c5f8b43]. Por favor verificar.

**Comment by mgiagante** [comment]
Arreglado en commit [master c5f8b43]. Por favor verificar.

**Comment by hugotonelli** [comment]
Verificado.
