### ISSUE TITLE
Eliminar usuario - Deshabilitar elegir como ganadora una oferta de un usuario eliminado

### ISSUE THREAD

**Issue by hugotonelli** [braiandickson/bestnid#26]
Se deberá tener especial cuidado para evitar que, en caso de que alguna de las ofertas de una subasta activa pertenezca a un usuario que se ha dado de baja, dichas ofertas no puedan visualizarse o (al menos) no puedan ser seleccionadas como ganadoras.

**Comment by mgiagante** [comment]
Se implementa arreglando el bug #30. Cerrar este issue al cerrar el bug.

**Comment by mgiagante** [comment]
Cerrando porque el bug #30 está cerrado.
