### ISSUE TITLE
High - Reporte de Subastas Concluidas - Excepción al obtener el reporte sin especificar fechas.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#32]
Pasos para reproducir:
1. Iniciar sesión con la cuenta de administrador.
2. Ir a Suabstas Concluidas.
3. Hacer click en Obtener Reporte/Buscar.

Resultado: Se produce una excepción causada por una comparación entre tipos incompatibles en los campos de fecha.
Esperado: Se muestran 0 resultados o los correspondientes a los valores por defecto de los campos de fecha.

Nota: Solo ocurre si se busca sin elegir fecha después de entrar a la vista. Si se hace una búsqueda válida antes, este error no se reproduce.

Se adjunta captura.
![concludedbug](https://cloud.githubusercontent.com/assets/5287175/8684051/9c9e86ae-2a4c-11e5-9f69-6062bec08a50.png)

**Comment by mgiagante** [comment]
Arreglado en commit be9126afc194660bd37a1a31458b9bad346ace71.

Por favor, verificar fix.

**Comment by hugotonelli** [comment]
Verificado.
