### ISSUE TITLE
Medium - Reporte de Subastas Concluidas - Las búsquedas que tienen ambas fechas iguales no traen como resultado las subastas concluidas en esa fecha.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#34]
Pasos para reproducir:
1. Asegurarse de que hay al menos una subasta concluida en el sistema.
2. Iniciar sesión como administrador.
3. Ir al reporte de subastas concluidas.
4. Ingresar la fecha en la que se eligió el ganador de una subasta existente en los campos "desde" y "hasta".
5. Hacer click en Obtener Reporte.
Resultado: No se encuentra ninguna subasta.
Resultado Esperado: Se encuentra la subasta cuya fecha de elección de ganador coincide con la ingresada en el paso 4.

**Comment by mgiagante** [comment]
Arreglado en commit commit 93fe7c5c398684551e84dbae9bb486c63a2b6c02. Por favor verificar.

**Comment by hugotonelli** [comment]
Confirmado. No ocurre más el error.
