### ISSUE TITLE
No puede crearse más de una subasta con la misma descripción.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#4]
Pasos para reproducir: 
1. Iniciar sesión en el sistema.
2. Crear una subasta con el texto 'test' como descripción del producto.
3. Intentar  crear otra subasta con el texto 'test' como descripción del producto.

Resultado: Una validación se asegura de que los contenidos del campo Descripción de las subastas sean únicos.
Resultado Esperado: El contenido de este campo puede repetirse de subasta a subasta.

**Comment by mgiagante** [comment]
Arreglado en el commit [master 1fa2506]

**Comment by braiandickson** [comment]
Revisado.
