### ISSUE TITLE
Registro - No se valida la longitud ni el formato del número de tarjeta de crédito.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#5]
Pasos para reproducir:
1. Ingresar al sitio como invitado.
2. Ir a Registrarse.
3. Ingresar un número de menos de 16 digitos, de más de 16 digitos, o letras.

Resultado: La entrada es aceptada.
Resultado Esperado: La entrada es rechazada por ser inválida para este campo.

**Comment by mgiagante** [comment]
Arreglado en commit 9f805d9629d308a5a4b9e3ea994e667c713a8742

**Comment by braiandickson** [comment]
Revisado.
