### ISSUE TITLE
Registro - No existe una longitud máxima para ninguno de los campos.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#6]
Pasos para reproducir:
1. Ingresar al sistema.
2. Ir a Registrate.
3. Ingresar una cadena de caracteres válida muy larga en cualquier campo (por ejemplo, nombre).
4. Aceptar el registro.

Resultado: Los datos son aceptados.
Resultado Esperado: Los datos son rechazados por una validación de longitud máxima.

**Comment by mgiagante** [comment]
Arreglado en commit 5b9ac1917f2a7df2bcebb49e08b2e88488f117d2. No se puso una longitud máxima para la contraseña. Ver si debería manejarse con Devise. Por ahora queda como está.

**Comment by hugotonelli** [comment]
Arreglo confirmado. El asunto de devise se solucionó con el  commit 47c567f.
