### ISSUE TITLE
Crear Subasta - El valor por defecto de la duración de subasta dice 15 en el combobox, pero luego de elegirlo la subasta se crea con duración 0.

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#7]
Pasos para reproducir:
1. Iniciar sesión.
2. Comenzar la creación de una subasta.
3. Llenar todos los campos con datos válidos, dejando la duración de la subasta con su valor por defecto en el combobox (15).
4. Confirmar la creación de la subasta.
Resultado: La fecha de expiración de la subasta es el día actual.
Esperado: La fecha de expiración es 15 días después del día actual.

**Comment by mgiagante** [comment]
Arreglado removiendo el prompt. commit 068e9d2fbf043b353ea16f8ac2db5559b6a8e524

**Comment by braiandickson** [comment]
Revisado.
