### ISSUE TITLE
Ordenamiento - Debe mostrarse el criterio de ordenamiento activo para la lista de subastas. 

### ISSUE THREAD

**Issue by mgiagante** [braiandickson/bestnid#9]
Cuando se elige un criterio de ordenamiento en el listado de subastas, el mismo debería mostrarse o resaltarse de alguna manera, de forma que el usuario pueda saber cuál es el criterio por el cual están ordenadas las subastas a cada momento.

**Comment by braiandickson** [comment]
Revisado.
